version: '3.8'
services:
  auth:
    image: sunyerim/sunjoo:auth
    container_name: sunjoo-server-auth
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8090"
  redis:
    image: sunyerim/sunjoo:redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - backup-redis:/data
volumes:
  backup-redis:
    driver: local
