version: '3.8'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  spring:
    image: auth
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - redis


