name: Auth CI/CD

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clear Gradle cache
        run: rm -rf ~/.gradle/caches/

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Auth Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/auth:latest

      - name: Build and push Redis Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/redis:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/redis:latest
      

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/sunjoo-server-auth
            docker-compose down
            docker pull ${{ secrets.DOCKER_USERNAME }}/auth:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/redis:latest
            docker-compose build
            docker-compose up -d
            docker network connect eureka-network sunjoo-server-auth-spring-1
            docker network connect eureka-network sunjoo-server-auth-redis-1
            docker restart sunjoo-server-auth-spring-1
            docker restart sunjoo-server-auth-redis-1
